# Datenbank

In [1]:
import pyodbc
import numpy as np
import pandas as pd

In [45]:
connStr = "Driver={ODBC Driver 17 for SQL Server};Server=WIN11-LK3;Database=Northwind;Trusted_Connection=yes;"
with pyodbc.connect(connStr) as conn:
    cursor = conn.cursor()

In [46]:
cursor = conn.cursor()

cursor.execute("SELECT * FROM Customers")

columns = [column[0] for column in cursor.description]
rows = cursor.fetchall()

In [47]:
cursor.description

(('CustomerID', str, None, 5, 5, 0, False),
 ('CompanyName', str, None, 40, 40, 0, False),
 ('ContactName', str, None, 30, 30, 0, True),
 ('ContactTitle', str, None, 30, 30, 0, True),
 ('Address', str, None, 60, 60, 0, True),
 ('City', str, None, 15, 15, 0, True),
 ('Region', str, None, 15, 15, 0, True),
 ('PostalCode', str, None, 10, 10, 0, True),
 ('Country', str, None, 15, 15, 0, True),
 ('Phone', str, None, 24, 24, 0, True),
 ('Fax', str, None, 24, 24, 0, True))

In [48]:
rows

[('ALFKI', 'Alfreds Futterkiste', 'Maria Anders', 'Sales Representative', 'Obere Str. 57', 'Berlin', None, '12209', 'Germany', '030-0074321', '030-0076545'),
 ('ANATR', 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Owner', 'Avda. de la Constitución 2222', 'México D.F.', None, '05021', 'Mexico', '(5) 555-4729', '(5) 555-3745'),
 ('ANTON', 'Antonio Moreno Taquería', 'Antonio Moreno', 'Owner', 'Mataderos  2312', 'México D.F.', None, '05023', 'Mexico', '(5) 555-3932', None),
 ('AROUT', 'Around the Horn', 'Thomas Hardy', 'Sales Representative', '120 Hanover Sq.', 'London', None, 'WA1 1DP', 'UK', '(171) 555-7788', '(171) 555-6750'),
 ('BERGS', 'Berglunds snabbköp', 'Christina Berglund', 'Order Administrator', 'Berguvsvägen  8', 'Luleå', None, 'S-958 22', 'Sweden', '0921-12 34 65', '0921-12 34 67'),
 ('BLAUS', 'Blauer See Delikatessen', 'Hanna Moos', 'Sales Representative', 'Forsterstr. 57', 'Mannheim', None, '68306', 'Germany', '0621-08460', '0621-08924'),
 ('BLONP', 'Blondesddsl père et fils', 'Frédérique Citeaux', 'Marketing Manager', '24, place Kléber', 'Strasbourg', None, '67000', 'France', '88.60.15.31', '88.60.15.32'),
 ('BOLID', 'Bólido Comidas preparadas', 'Martín Sommer', 'Owner', 'C/ Araquil, 67', 'Madrid', None, '28023', 'Spain', '(91) 555 22 82', '(91) 555 91 99'),
 ('BONAP', "Bon app'", 'Laurence Lebihan', 'Owner', '12, rue des Bouchers', 'Marseille', None, '13008', 'France', '91.24.45.40', '91.24.45.41'),
 ('BOTTM', 'Bottom-Dollar Markets', 'Elizabeth Lincoln', 'Accounting Manager', '23 Tsawassen Blvd.', 'Tsawassen', 'BC', 'T2F 8M4', 'Canada', '(604) 555-4729', '(604) 555-3745'),
 ('BSBEV', "B's Beverages", 'Victoria Ashworth', 'Sales Representative', 'Fauntleroy Circus', 'London', None, 'EC2 5NT', 'UK', '(171) 555-1212', None),
 ('CACTU', 'Cactus Comidas para llevar', 'Patricio Simpson', 'Sales Agent', 'Cerrito 333', 'Buenos Aires', None, '1010', 'Argentina', '(1) 135-5555', '(1) 135-4892'),
 ('CENTC', 'Centro comercial Moctezuma', 'Francisco Chang', 'Marketing Manager', 'Sierras de Granada 9993', 'México D.F.', None, '05022', 'Mexico', '(5) 555-3392', '(5) 555-7293'),
 ('CHOPS', 'Chop-suey Chinese', 'Yang Wang', 'Owner', 'Hauptstr. 29', 'Bern', None, '3012', 'Switzerland', '0452-076545', None),
 ('COMMI', 'Comércio Mineiro', 'Pedro Afonso', 'Sales Associate', 'Av. dos Lusíadas, 23', 'Sao Paulo', 'SP', '05432-043', 'Brazil', '(11) 555-7647', None),
 ('GROSR', 'GROSELLA-Restaurante', 'Manuel Pereira', 'Owner', '5ª Ave. Los Palos Grandes', 'Caracas', 'DF', '1081', 'Venezuela', '(2) 283-2951', '(2) 283-3397'),
 ('HANAR', 'Hanari Carnes', 'Mario Pontes', 'Accounting Manager', 'Rua do Paço, 67', 'Rio de Janeiro', 'RJ', '05454-876', 'Brazil', '(21) 555-0091', '(21) 555-8765'),
 ('HILAA', 'HILARION-Abastos', 'Carlos Hernández', 'Sales Representative', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal', 'Táchira', '5022', 'Venezuela', '(5) 555-1340', '(5) 555-1948'),
 ('HUNGC', 'Hungry Coyote Import Store', 'Yoshi Latimer', 'Sales Representative', 'City Center Plaza 516 Main St.', 'Elgin', 'OR', '97827', 'USA', '(503) 555-6874', '(503) 555-2376'),
 ('HUNGO', 'Hungry Owl All-Night Grocers', 'Patricia McKenna', 'Sales Associate', '8 Johnstown Road', 'Cork', 'Co. Cork', None, 'Ireland', '2967 542', '2967 3333'),
 ('ISLAT', 'Island Trading', 'Helen Bennett', 'Marketing Manager', 'Garden House Crowther Way', 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK', '(198) 555-8888', None),
 ('KOENE', 'Königlich Essen', 'Philip Cramer', 'Sales Associate', 'Maubelstr. 90', 'Brandenburg', None, '14776', 'Germany', '0555-09876', None),
 ('LACOR', "La corne d'abondance", 'Daniel Tonini', 'Sales Representative', "67, avenue de l'Europe", 'Versailles', None, '78000', 'France', '30.59.84.10', '30.59.85.11'),
 ('LAMAI', "La maison d'Asie", 'Annette Roulet', 'Sales Manager', '1 rue Alsace-Lorraine', 'Toulouse', None, '31000', 'France', '61.77.61.10', '61.77.61.11'),
 ('LAUGB', 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', 'Marketing Assistant', '1900 Oak St.', 'Vancouver', 'BC', 'V3F 2K1', 'Canada', '(604) 555-3392', '(604) 555-7293'),
 ('LAZYK', 'Lazy K Kountry Store', 'John Steel', 'Marketing Manager', '12 Orchestra Terrace', 'Walla Walla', 'WA', '99362', 'USA', '(509) 555-7969', '(509) 555-6221'),
 ('LEHMS', 'Lehmanns Marktstand', 'Renate Messner', 'Sales Representative', 'Magazinweg 7', 'Frankfurt a.M.', None, '60528', 'Germany', '069-0245984', '069-0245874'),
 ('LETSS', "Let's Stop N Shop", 'Jaime Yorres', 'Owner', '87 Polk St. Suite 5', 'San Francisco', 'CA', '94117', 'USA', '(415) 555-5938', None),
 ('LILAS', 'LILA-Supermercado', 'Carlos González', 'Accounting Manager', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto', 'Lara', '3508', 'Venezuela', '(9) 331-6954', '(9) 331-7256'),
 ('QUEEN', 'Queen Cozinha', 'Lúcia Carvalho', 'Marketing Assistant', 'Alameda dos Canàrios, 891', 'Sao Paulo', 'SP', '05487-020', 'Brazil', '(11) 555-1189', None),
 ('QUICK', 'QUICK-Stop', 'Horst Kloss', 'Accounting Manager', 'Taucherstraße 10', 'Cunewalde', None, '01307', 'Germany', '0372-035188', None),
 ('RANCH', 'Rancho grande', 'Sergio Gutiérrez', 'Sales Representative', 'Av. del Libertador 900', 'Buenos Aires', None, '1010', 'Argentina', '(1) 123-5555', '(1) 123-5556'),
 ('RATTC', 'Rattlesnake Canyon Grocery', 'Paula Wilson', 'Assistant Sales Representative', '2817 Milton Dr.', 'Albuquerque', 'NM', '87110', 'USA', '(505) 555-5939', '(505) 555-3620'),
 ('REGGC', 'Reggiani Caseifici', 'Maurizio Moroni', 'Sales Associate', 'Strada Provinciale 124', 'Reggio Emilia', None, '42100', 'Italy', '0522-556721', '0522-556722'),
 ('RICAR', 'Ricardo Adocicados', 'Janete Limeira', 'Assistant Sales Agent', 'Av. Copacabana, 267', 'Rio de Janeiro', 'RJ', '02389-890', 'Brazil', '(21) 555-3412', None),
 ('RICSU', 'Richter Supermarkt', 'Michael Holz', 'Sales Manager', 'Grenzacherweg 237', 'Genève', None, '1203', 'Switzerland', '0897-034214', None),
 ('ROMEY', 'Romero y tomillo', 'Alejandra Camino', 'Accounting Manager', 'Gran Vía, 1', 'Madrid', None, '28001', 'Spain', '(91) 745 6200', '(91) 745 6210'),
 ('SANTG', 'Santé Gourmet', 'Jonas Bergulfsen', 'Owner', 'Erling Skakkes gate 78', 'Stavern', None, '4110', 'Norway', '07-98 92 35', '07-98 92 47'),
 ('SAVEA', 'Save-a-lot Markets', 'Jose Pavarotti', 'Sales Representative', '187 Suffolk Ln.', 'Boise', 'ID', '83720', 'USA', '(208) 555-8097', None),
 ('SEVES', 'Seven Seas Imports', 'Hari Kumar', 'Sales Manager', '90 Wadhurst Rd.', 'London', None, 'OX15 4NB', 'UK', '(171) 555-1717', '(171) 555-5646'),
 ('SIMOB', 'Simons bistro', 'Jytte Petersen', 'Owner', 'Vinbæltet 34', 'Kobenhavn', None, '1734', 'Denmark', '31 12 34 56', '31 13 35 57'),
 ('SPECD', 'Spécialités du monde', 'Dominique Perrier', 'Marketing Manager', '25, rue Lauriston', 'Paris', None, '75016', 'France', '(1) 47.55.60.10', '(1) 47.55.60.20'),
 ('SPLIR', 'Split Rail Beer & Ale', 'Art Braunschweiger', 'Sales Manager', 'P.O. Box 555', 'Lander', 'WY', '82520', 'USA', '(307) 555-4680', '(307) 555-6525'),
 ('CONSH', 'Consolidated Holdings', 'Elizabeth Brown', 'Sales Representative', 'Berkeley Gardens 12  Brewery', 'London', None, 'WX1 6LT', 'UK', '(171) 555-2282', '(171) 555-9199'),
 ('DRACD', 'Drachenblut Delikatessen', 'Sven Ottlieb', 'Order Administrator', 'Walserweg 21', 'Aachen', None, '52066', 'Germany', '0241-039123', '0241-059428'),
 ('DUMON', 'Du monde entier', 'Janine Labrune', 'Owner', '67, rue des Cinquante Otages', 'Nantes', None, '44000', 'France', '40.67.88.88', '40.67.89.89'),
 ('EASTC', 'Eastern Connection', 'Ann Devon', 'Sales Agent', '35 King George', 'London', None, 'WX3 6FW', 'UK', '(171) 555-0297', '(171) 555-3373'),
 ('ERNSH', 'Ernst Handel', 'Roland Mendel', 'Sales Manager', 'Kirchgasse 6', 'Graz', None, '8010', 'Austria', '7675-3425', '7675-3426'),
 ('FAMIA', 'Familia Arquibaldo', 'Aria Cruz', 'Marketing Assistant', 'Rua Orós, 92', 'Sao Paulo', 'SP', '05442-030', 'Brazil', '(11) 555-9857', None),
 ('FISSA', 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'Accounting Manager', 'C/ Moralzarzal, 86', 'Madrid', None, '28034', 'Spain', '(91) 555 94 44', '(91) 555 55 93'),
 ('FOLIG', 'Folies gourmandes', 'Martine Rancé', 'Assistant Sales Agent', '184, chaussée de Tournai', 'Lille', None, '59000', 'France', '20.16.10.16', '20.16.10.17'),
 ('FOLKO', 'Folk och fä HB', 'Maria Larsson', 'Owner', 'Åkergatan 24', 'Bräcke', None, 'S-844 67', 'Sweden', '0695-34 67 21', None),
 ('FRANK', 'Frankenversand', 'Peter Franken', 'Marketing Manager', 'Berliner Platz 43', 'München', None, '80805', 'Germany', '089-0877310', '089-0877451'),
 ('FRANR', 'France restauration', 'Carine Schmitt', 'Marketing Manager', '54, rue Royale', 'Nantes', None, '44000', 'France', '40.32.21.21', '40.32.21.20'),
 ('FRANS', 'Franchi S.p.A.', 'Paolo Accorti', 'Sales Representative', 'Via Monte Bianco 34', 'Torino', None, '10100', 'Italy', '011-4988260', '011-4988261'),
 ('FURIB', 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Sales Manager', 'Jardim das rosas n. 32', 'Lisboa', None, '1675', 'Portugal', '(1) 354-2534', '(1) 354-2535'),
 ('GALED', 'Galería del gastrónomo', 'Eduardo Saavedra', 'Marketing Manager', 'Rambla de Cataluña, 23', 'Barcelona', None, '08022', 'Spain', '(93) 203 4560', '(93) 203 4561'),
 ('GODOS', 'Godos Cocina Típica', 'José Pedro Freyre', 'Sales Manager', 'C/ Romero, 33', 'Sevilla', None, '41101', 'Spain', '(95) 555 82 82', None),
 ('GOURL', 'Gourmet Lanchonetes', 'André Fonseca', 'Sales Associate', 'Av. Brasil, 442', 'Campinas', 'SP', '04876-786', 'Brazil', '(11) 555-9482', None),
 ('GREAL', 'Great Lakes Food Market', 'Howard Snyder', 'Marketing Manager', '2732 Baker Blvd.', 'Eugene', 'OR', '97403', 'USA', '(503) 555-7555', None),
 ('LINOD', 'LINO-Delicateses', 'Felipe Izquierdo', 'Owner', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita', 'Nueva Esparta', '4980', 'Venezuela', '(8) 34-56-12', '(8) 34-93-93'),
 ('LONEP', 'Lonesome Pine Restaurant', 'Fran Wilson', 'Sales Manager', '89 Chiaroscuro Rd.', 'Portland', 'OR', '97219', 'USA', '(503) 555-9573', '(503) 555-9646'),
 ('MAGAA', 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Marketing Manager', 'Via Ludovico il Moro 22', 'Bergamo', None, '24100', 'Italy', '035-640230', '035-640231'),
 ('MAISD', 'Maison Dewey', 'Catherine Dewey', 'Sales Agent', 'Rue Joseph-Bens 532', 'Bruxelles', None, 'B-1180', 'Belgium', '(02) 201 24 67', '(02) 201 24 68'),
 ('MEREP', 'Mère Paillarde', 'Jean Fresnière', 'Marketing Assistant', '43 rue St. Laurent', 'Montréal', 'Québec', 'H1J 1C3', 'Canada', '(514) 555-8054', '(514) 555-8055'),
 ('MORGK', 'Morgenstern Gesundkost', 'Alexander Feuer', 'Marketing Assistant', 'Heerstr. 22', 'Leipzig', None, '04179', 'Germany', '0342-023176', None),
 ('NORTS', 'North/South', 'Simon Crowther', 'Sales Associate', 'South House 300 Queensbridge', 'London', None, 'SW7 1RZ', 'UK', '(171) 555-7733', '(171) 555-2530'),
 ('OCEAN', 'Océano Atlántico Ltda.', 'Yvonne Moncada', 'Sales Agent', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires', None, '1010', 'Argentina', '(1) 135-5333', '(1) 135-5535'),
 ('OLDWO', 'Old World Delicatessen', 'Rene Phillips', 'Sales Representative', '2743 Bering St.', 'Anchorage', 'AK', '99508', 'USA', '(907) 555-7584', '(907) 555-2880'),
 ('OTTIK', 'Ottilies Käseladen', 'Henriette Pfalzheim', 'Owner', 'Mehrheimerstr. 369', 'Köln', None, '50739', 'Germany', '0221-0644327', '0221-0765721'),
 ('PARIS', 'Paris spécialités', 'Marie Bertrand', 'Owner', '265, boulevard Charonne', 'Paris', None, '75012', 'France', '(1) 42.34.22.66', '(1) 42.34.22.77'),
 ('PERIC', 'Pericles Comidas clásicas', 'Guillermo Fernández', 'Sales Representative', 'Calle Dr. Jorge Cash 321', 'México D.F.', None, '05033', 'Mexico', '(5) 552-3745', '(5) 545-3745'),
 ('PICCO', 'Piccolo und mehr', 'Georg Pipps', 'Sales Manager', 'Geislweg 14', 'Salzburg', None, '5020', 'Austria', '6562-9722', '6562-9723'),
 ('PPEDV', 'ppedv', '', None, None, None, None, None, None, None, None),
 ('PRINI', 'Princesa Isabel Vinhos', 'Isabel de Castro', 'Sales Representative', 'Estrada da saúde n. 58', 'Lisboa', None, '1756', 'Portugal', '(1) 356-5634', None),
 ('QUEDE', 'Que Delícia', 'Bernardo Batista', 'Accounting Manager', 'Rua da Panificadora, 12', 'Rio de Janeiro', 'RJ', '02389-673', 'Brazil', '(21) 555-4252', '(21) 555-4545'),
 ('SUPRD', 'Suprêmes délices', 'Pascale Cartrain', 'Accounting Manager', 'Boulevard Tirou, 255', 'Charleroi', None, 'B-6000', 'Belgium', '(071) 23 67 22 20', '(071) 23 67 22 21'),
 ('THEBI', 'The Big Cheese', 'Liz Nixon', 'Marketing Manager', '89 Jefferson Way Suite 2', 'Portland', 'OR', '97201', 'USA', '(503) 555-3612', None),
 ('THECR', 'The Cracker Box', 'Liu Wong', 'Marketing Assistant', '55 Grizzly Peak Rd.', 'Butte', 'MT', '59801', 'USA', '(406) 555-5834', '(406) 555-8083'),
 ('TOMSP', 'Toms Spezialitäten', 'Karin Josephs', 'Marketing Manager', 'Luisenstr. 48', 'Münster', None, '44087', 'Germany', '0251-031259', '0251-035695'),
 ('TORTU', 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Owner', 'Avda. Azteca 123', 'México D.F.', None, '05033', 'Mexico', '(5) 555-2933', None),
 ('TRADH', 'Tradição Hipermercados', 'Anabela Domingues', 'Sales Representative', 'Av. Inês de Castro, 414', 'Sao Paulo', 'SP', '05634-030', 'Brazil', '(11) 555-2167', '(11) 555-2168'),
 ('TRAIH', "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', 'Sales Associate', '722 DaVinci Blvd.', 'Kirkland', 'WA', '98034', 'USA', '(206) 555-8257', '(206) 555-2174'),
 ('VAFFE', 'Vaffeljernet', 'Palle Ibsen', 'Sales Manager', 'Smagsloget 45', 'Århus', None, '8200', 'Denmark', '86 21 32 43', '86 22 33 44'),
 ('VICTE', 'Victuailles en stock', 'Mary Saveley', 'Sales Agent', '2, rue du Commerce', 'Lyon', None, '69004', 'France', '78.32.54.86', '78.32.54.87'),
 ('VINET', 'Vins et alcools Chevalier', 'Paul Henriot', 'Accounting Manager', "59 rue de l'Abbaye", 'Reims', None, '51100', 'France', '26.47.15.10', '26.47.15.11'),
 ('WANDK', 'Die Wandernde Kuh', 'Rita Müller', 'Sales Representative', 'Adenauerallee 900', 'Stuttgart', None, '70563', 'Germany', '0711-020361', '0711-035428'),
 ('WARTH', 'Wartian Herkku', 'Pirkko Koskitalo', 'Accounting Manager', 'Torikatu 38', 'Oulu', None, '90110', 'Finland', '981-443655', '981-443655'),
 ('WELLI', 'Wellington Importadora', 'Paula Parente', 'Sales Manager', 'Rua do Mercado, 12', 'Resende', 'SP', '08737-363', 'Brazil', '(14) 555-8122', None),
 ('WHITC', 'White Clover Markets', 'Karl Jablonski', 'Owner', '305 - 14th Ave. S. Suite 3B', 'Seattle', 'WA', '98128', 'USA', '(206) 555-4112', '(206) 555-4115'),
 ('WILMK', 'Wilman Kala', 'Matti Karttunen', 'Owner/Marketing Assistant', 'Keskuskatu 45', 'Helsinki', None, '21240', 'Finland', '90-224 8858', '90-224 8858'),
 ('WOLZA', 'Wolski  Zajazd', 'Zbyszek Piestrzeniewicz', 'Owner', 'ul. Filtrowa 68', 'Warszawa', None, '01-012', 'Poland', '(26) 642-7012', '(26) 642-7012')]

In [49]:
pd.DataFrame.from_records(rows, columns=columns)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,NaN,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,NaN,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,NaN,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...,...
87,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,NaN,90110,Finland,981-443655,981-443655
88,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,SP,08737-363,Brazil,(14) 555-8122,NaN
89,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
90,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,NaN,21240,Finland,90-224 8858,90-224 8858
91,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,NaN,01-012,Poland,(26) 642-7012,(26) 642-7012

In [9]:
pd.read_sql("SELECT * FROM Customers", con=conn)

C:\Users\lk3\AppData\Local\Temp\ipykernel_11920\3873916040.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SELECT * FROM Customers", con=conn)

,CustomerID,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,NaN,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,NaN,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,NaN,05023,Mexico,(5) 555-3932,NaN
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,NaN,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,NaN,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...,...
87,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,NaN,90110,Finland,981-443655,981-443655
88,WELLI,Wellington Importadora,Paula Parente,Sales Manager,"Rua do Mercado, 12",Resende,SP,08737-363,Brazil,(14) 555-8122,NaN
89,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
90,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,NaN,21240,Finland,90-224 8858,90-224 8858
91,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,NaN,01-012,Poland,(26) 642-7012,(26) 642-7012

# Sharepoint (API)

In [28]:
import requests

In [41]:
req = requests.get("https://open.er-api.com/v6/latest/USD")

In [42]:
json = req.json()

In [44]:
pd.DataFrame.from_dict(json["rates"], orient="index")

              0
USD    1.000000
AED    3.672500
AFN   63.325943
ALL   82.688149
AMD  377.024118
..          ...
YER  238.299157
ZAR   16.488763
ZMW   19.483778
ZWG   25.504600
ZWL   25.504600

[166 rows x 1 columns]

# Enumerate

In [3]:
data = pd.read_csv("Data/PopulationDataFertig.csv")

In [8]:
i = 0
for country in data["Country"]:
    print(f"{i}: {country}")
    i += 1

0: China
1: India
2: United States
3: Indonesia
4: Pakistan
5: Brazil
6: Nigeria
7: Bangladesh
8: Russia
9: Mexico
10: Japan
11: Ethiopia
12: Philippines
13: Egypt
14: Vietnam
15: DR Congo
16: Turkey
17: Iran
18: Germany
19: Thailand
20: United Kingdom
21: France
22: Italy
23: Tanzania
24: South Africa
25: Myanmar
26: Kenya
27: South Korea
28: Colombia
29: Spain
30: Uganda
31: Argentina
32: Algeria
33: Sudan
34: Ukraine
35: Iraq
36: Afghanistan
37: Poland
38: Canada
39: Morocco
40: Saudi Arabia
41: Uzbekistan
42: Peru
43: Angola
44: Malaysia
45: Mozambique
46: Ghana
47: Yemen
48: Nepal
49: Venezuela
50: Madagascar
51: Cameroon
52: Côte d'Ivoire
53: North Korea
54: Australia
55: Niger
56: Taiwan
57: Sri Lanka
58: Burkina Faso
59: Mali
60: Romania
61: Malawi
62: Chile
63: Kazakhstan
64: Zambia
65: Guatemala
66: Ecuador
67: Syria
68: Netherlands
69: Senegal
70: Cambodia
71: Chad
72: Somalia
73: Zimbabwe
74: Guinea
75: Rwanda
76: Benin
77: Burundi
78: Tunisia
79: Bolivia
80: Belgium
81: Haiti
82: Cuba
83: South Sudan
84: Dominican Republic
85: Czech Republic (Czechia)
86: Greece
87: Jordan
88: Portugal
89: Azerbaijan
90: Sweden
91: Honduras
92: United Arab Emirates
93: Hungary
94: Tajikistan
95: Belarus
96: Austria
97: Papua New Guinea
98: Serbia
99: Israel
100: Switzerland
101: Togo
102: Sierra Leone
103: Hong Kong
104: Laos
105: Paraguay
106: Bulgaria
107: Libya
108: Lebanon
109: Nicaragua
110: Kyrgyzstan
111: El Salvador
112: Turkmenistan
113: Singapore
114: Denmark
115: Finland
116: Congo
117: Slovakia
118: Norway
119: Oman
120: State of Palestine
121: Costa Rica
122: Liberia
123: Ireland
124: Central African Republic
125: New Zealand
126: Mauritania
127: Panama
128: Kuwait
129: Croatia
130: Moldova
131: Georgia
132: Eritrea
133: Uruguay
134: Bosnia and Herzegovina
135: Mongolia
136: Armenia
137: Jamaica
138: Qatar
139: Albania
140: Puerto Rico
141: Lithuania
142: Namibia
143: Gambia
144: Botswana
145: Gabon
146: Lesotho
147: North Macedonia
148: Slovenia
149: Guinea-Bissau
150: Latvia
151: Bahrain
152: Equatorial Guinea
153: Trinidad and Tobago
154: Estonia
155: Timor-Leste
156: Mauritius
157: Cyprus
158: Eswatini
159: Djibouti
160: Fiji
161: Réunion
162: Comoros
163: Guyana
164: Bhutan
165: Solomon Islands
166: Macao
167: Montenegro
168: Luxembourg
169: Western Sahara
170: Suriname
171: Cabo Verde
172: Micronesia
173: Maldives
174: Malta
175: Brunei
176: Guadeloupe
177: Belize
178: Bahamas
179: Martinique
180: Iceland
181: Vanuatu
182: French Guiana
183: Barbados
184: New Caledonia
185: French Polynesia
186: Mayotte
187: Sao Tome & Principe
188: Samoa
189: Saint Lucia
190: Channel Islands
191: Guam
192: Curaçao
193: Kiribati
194: Grenada
195: St. Vincent & Grenadines
196: Aruba
197: Tonga
198: U.S. Virgin Islands
199: Seychelles
200: Antigua and Barbuda
201: Isle of Man
202: Andorra
203: Dominica
204: Cayman Islands
205: Bermuda
206: Marshall Islands
207: Northern Mariana Islands
208: Greenland
209: American Samoa
210: Saint Kitts & Nevis
211: Faeroe Islands
212: Sint Maarten
213: Monaco
214: Turks and Caicos
215: Saint Martin
216: Liechtenstein
217: San Marino
218: Gibraltar
219: British Virgin Islands
220: Caribbean Netherlands
221: Palau
222: Cook Islands
223: Anguilla
224: Tuvalu
225: Wallis & Futuna
226: Nauru
227: Saint Barthelemy
228: Saint Helena
229: Saint Pierre & Miquelon
230: Montserrat
231: Falkland Islands
232: Niue
233: Tokelau
234: Vatican State

In [9]:
for i, country in enumerate(data["Country"]):  # enumerate: Fügt zu einer for-Schleife einen Index hinzu
    print(f"{i}: {country}")

0: China
1: India
2: United States
3: Indonesia
4: Pakistan
5: Brazil
6: Nigeria
7: Bangladesh
8: Russia
9: Mexico
10: Japan
11: Ethiopia
12: Philippines
13: Egypt
14: Vietnam
15: DR Congo
16: Turkey
17: Iran
18: Germany
19: Thailand
20: United Kingdom
21: France
22: Italy
23: Tanzania
24: South Africa
25: Myanmar
26: Kenya
27: South Korea
28: Colombia
29: Spain
30: Uganda
31: Argentina
32: Algeria
33: Sudan
34: Ukraine
35: Iraq
36: Afghanistan
37: Poland
38: Canada
39: Morocco
40: Saudi Arabia
41: Uzbekistan
42: Peru
43: Angola
44: Malaysia
45: Mozambique
46: Ghana
47: Yemen
48: Nepal
49: Venezuela
50: Madagascar
51: Cameroon
52: Côte d'Ivoire
53: North Korea
54: Australia
55: Niger
56: Taiwan
57: Sri Lanka
58: Burkina Faso
59: Mali
60: Romania
61: Malawi
62: Chile
63: Kazakhstan
64: Zambia
65: Guatemala
66: Ecuador
67: Syria
68: Netherlands
69: Senegal
70: Cambodia
71: Chad
72: Somalia
73: Zimbabwe
74: Guinea
75: Rwanda
76: Benin
77: Burundi
78: Tunisia
79: Bolivia
80: Belgium
81: Haiti
82: Cuba
83: South Sudan
84: Dominican Republic
85: Czech Republic (Czechia)
86: Greece
87: Jordan
88: Portugal
89: Azerbaijan
90: Sweden
91: Honduras
92: United Arab Emirates
93: Hungary
94: Tajikistan
95: Belarus
96: Austria
97: Papua New Guinea
98: Serbia
99: Israel
100: Switzerland
101: Togo
102: Sierra Leone
103: Hong Kong
104: Laos
105: Paraguay
106: Bulgaria
107: Libya
108: Lebanon
109: Nicaragua
110: Kyrgyzstan
111: El Salvador
112: Turkmenistan
113: Singapore
114: Denmark
115: Finland
116: Congo
117: Slovakia
118: Norway
119: Oman
120: State of Palestine
121: Costa Rica
122: Liberia
123: Ireland
124: Central African Republic
125: New Zealand
126: Mauritania
127: Panama
128: Kuwait
129: Croatia
130: Moldova
131: Georgia
132: Eritrea
133: Uruguay
134: Bosnia and Herzegovina
135: Mongolia
136: Armenia
137: Jamaica
138: Qatar
139: Albania
140: Puerto Rico
141: Lithuania
142: Namibia
143: Gambia
144: Botswana
145: Gabon
146: Lesotho
147: North Macedonia
148: Slovenia
149: Guinea-Bissau
150: Latvia
151: Bahrain
152: Equatorial Guinea
153: Trinidad and Tobago
154: Estonia
155: Timor-Leste
156: Mauritius
157: Cyprus
158: Eswatini
159: Djibouti
160: Fiji
161: Réunion
162: Comoros
163: Guyana
164: Bhutan
165: Solomon Islands
166: Macao
167: Montenegro
168: Luxembourg
169: Western Sahara
170: Suriname
171: Cabo Verde
172: Micronesia
173: Maldives
174: Malta
175: Brunei
176: Guadeloupe
177: Belize
178: Bahamas
179: Martinique
180: Iceland
181: Vanuatu
182: French Guiana
183: Barbados
184: New Caledonia
185: French Polynesia
186: Mayotte
187: Sao Tome & Principe
188: Samoa
189: Saint Lucia
190: Channel Islands
191: Guam
192: Curaçao
193: Kiribati
194: Grenada
195: St. Vincent & Grenadines
196: Aruba
197: Tonga
198: U.S. Virgin Islands
199: Seychelles
200: Antigua and Barbuda
201: Isle of Man
202: Andorra
203: Dominica
204: Cayman Islands
205: Bermuda
206: Marshall Islands
207: Northern Mariana Islands
208: Greenland
209: American Samoa
210: Saint Kitts & Nevis
211: Faeroe Islands
212: Sint Maarten
213: Monaco
214: Turks and Caicos
215: Saint Martin
216: Liechtenstein
217: San Marino
218: Gibraltar
219: British Virgin Islands
220: Caribbean Netherlands
221: Palau
222: Cook Islands
223: Anguilla
224: Tuvalu
225: Wallis & Futuna
226: Nauru
227: Saint Barthelemy
228: Saint Helena
229: Saint Pierre & Miquelon
230: Montserrat
231: Falkland Islands
232: Niue
233: Tokelau
234: Vatican State