# Pandas

Python Advanced Data Analysis Toolkit

Hauptwerkzeug zur Verarbeitung von Daten

In [1]:
import numpy as np
import pandas as pd

## Serie

Liste von Werten

Enthält ein Numpy Array darunter, und kann auch alle Operationen von einem Numpy Array verwenden

In [4]:
s = pd.Series([0.38, 83.7, 8.6, 9])  # Die Zahlen alleine sagen nicht viel aus

In [5]:
s

0     0.38
1    83.70
2     8.60
3     9.00
dtype: float64

In [6]:
s.name = "Einwohnerzahlen Europa"

In [9]:
s

0     0.38
1    83.70
2     8.60
3     9.00
Name: Einwohnerzahlen Europa, dtype: float64

In [26]:
s.index = ["LI", "DE", "CH", "AT"]

In [27]:
s

LI     0.38
DE    83.70
CH     8.60
AT     9.00
Name: Einwohnerzahlen Europa, dtype: float64

In [25]:
s.index = range(len(s))  # Index auf Zahlen zurücksetzen

In [28]:
s

LI     0.38
DE    83.70
CH     8.60
AT     9.00
Name: Einwohnerzahlen Europa, dtype: float64

### Index

In [38]:
s["AT"]  # Stringbasierter Index

np.float64(9.0)

In [42]:
s[0]  # Zahlenbasierter Index nicht mehr möglich

KeyError: 0

In [45]:
s["DE":"AT"]  # Obergrenze ist hier inkludiert

DE    83.7
CH     8.6
AT     9.0
Name: Einwohnerzahlen Europa, dtype: float64

In [46]:
s["CH":]

CH    8.6
AT    9.0
Name: Einwohnerzahlen Europa, dtype: float64

In [49]:
s.index

Index(['LI', 'DE', 'CH', 'AT'], dtype='str')

### Numpy Operationen

In [30]:
s.dtype

dtype('float64')

In [31]:
s.size

4

In [32]:
s.ndim

1

In [33]:
s.shape

(4,)

In [35]:
s.values  # Das unterliegende Numpy Array

array([ 0.38, 83.7 ,  8.6 ,  9.  ])

In [36]:
s.mean()

np.float64(25.419999999999998)

In [37]:
s.values.mean()

np.float64(25.419999999999998)

### Vektorisierung

In [51]:
s > 5

LI    False
DE     True
CH     True
AT     True
Name: Einwohnerzahlen Europa, dtype: bool

In [52]:
s[s > 5]

DE    83.7
CH     8.6
AT     9.0
Name: Einwohnerzahlen Europa, dtype: float64

In [53]:
s.mean()

np.float64(25.419999999999998)

In [54]:
s[s > s.mean()]

DE    83.7
Name: Einwohnerzahlen Europa, dtype: float64

## DataFrame

Effektiv eine Tabelle

Generell wird ein Datenset von externen Daten geladen, und dann mithilfe von Python Code verarbeitet

In [55]:
pd.DataFrame({"Spalte 1": [1, 2, 3], "Spalte 2": [4, 5, 6], "Spalte 3": [7, 8, 9]})

   Spalte 1  Spalte 2  Spalte 3
0         1         4         7
1         2         5         8
2         3         6         9

### read_csv

Liest Daten aus einer CSV-Datei ein

Wird über Parameter konfiguriert:
- delimiter
- thousands
- decimal
- parse_dates
- index_col
- ...

In [124]:
data = pd.read_csv("Data/PopulationData.csv", delimiter=";", thousands=",", decimal=".")

In [125]:
data

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [126]:
data.info()  # Überblick über das DataFrame verschaffen

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   #                        235 non-null    int64
 1   Country (or dependency)  235 non-null    str
 2   Population(2020)         235 non-null    int64
 3   YearlyChange             235 non-null    str
 4   NetChange                235 non-null    int64
 5   Density(P/Km²)           235 non-null    int64
 6   Land Area(Km²)           235 non-null    int64
 7   Migrants(net)            201 non-null    float64
 8   Fert.Rate                235 non-null    str
 9   Med.Age                  235 non-null    str
 10  UrbanPop %               235 non-null    str
 11  WorldShare               235 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 22.2 KB

In [127]:
data.head(10)  # Die obersten 10 Datensätze

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
5,6,Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
6,7,Nigeria,206139589,2.58 %,5175990,226,910770,-60000.0,5.4,18,52 %,2.64 %
7,8,Bangladesh,164689383,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %
8,9,Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
9,10,Mexico,128932753,1.06 %,1357224,66,1943950,-60000.0,2.1,29,84 %,1.65 %

In [128]:
data.tail(10)  # Die untersten 10 Datensätze

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
225,226,Wallis & Futuna,11239,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
226,227,Nauru,10824,0.63 %,68,541,20,NaN,N.A.,N.A.,N.A.,0.00 %
227,228,Saint Barthelemy,9877,0.30 %,30,470,21,NaN,N.A.,N.A.,0 %,0.00 %
228,229,Saint Helena,6077,0.30 %,18,16,390,NaN,N.A.,N.A.,27 %,0.00 %
229,230,Saint Pierre & Miquelon,5794,-0.48 %,-28,25,230,NaN,N.A.,N.A.,100 %,0.00 %
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

### Probleme mit dem Datenset

DataFrame:
- Schlechte Spaltennamen
- Doppelter Index

Daten selbst:
- Prozentzeichen
- Leere Felder (NaN)
- N.A. (String)
- Datentypen optimieren
- Tausenderzeichen/Dezimalzeichen

### Index

- set_index(Spaltenname)
- data.index = Listenvariable
- bei read_csv kann auch direkt der Index angegeben werden mit index_col = Spaltenname

In [129]:
pd.read_csv("Data/PopulationData.csv", delimiter=";", thousands=",", decimal=".", index_col="Country (or dependency)").head(1)

,#,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,,
China,1,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %

In [130]:
data.head(1)

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %

In [131]:
# WICHTIG: Wenn eine Funktion das DataFrame anspricht, wird die Änderung niemals auf das Original übernommen (es wird immer eine Kopie erzeugt)
# 2 Optionen: inplace, Zuweisung
data.set_index("Country (or dependency)", inplace=True)

# data.set_index(data.columns[0])  # Setzt immer die Linkste Spalte der Tabelle als Index

In [132]:
data

,#,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,,
China,1,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,2,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,3,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,4,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,5,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...
Montserrat,231,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,232,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,233,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,234,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,235,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [133]:
data.index.name = "Country"

In [134]:
data

,#,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country,,,,,,,,,,,
China,1,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,2,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,3,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,4,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,5,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...
Montserrat,231,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,232,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,233,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,234,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,235,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

### Spalten bearbeiten
- drop: Spalten löschen
- rename: Spalten umbenennen

In [135]:
data.drop(columns=["#"], inplace=True)  # Hier können auch Zeilen gelöscht werden

In [136]:
data

,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [142]:
previousNames = data.columns

names = {
    "Population(2020)": "Pop",
    "Density(P/Km²)": "Density",
    "Land Area(Km²)": "LandArea",
    "Migrants(net)": "MigrantsNet",
    "Fert.Rate": "FertRate",
    "Med.Age": "MedAge",
    "UrbanPop %": "UrbanPop"
}

data.rename(columns=names, inplace=True)  # Hier können auch Zeilen umbenannt werden

In [143]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [139]:
previousNames

Index(['Population(2020)', 'YearlyChange', 'NetChange', 'Density(P/Km²)',
       'Land Area(Km²)', 'Migrants(net)', 'Fert.Rate', 'Med.Age', 'UrbanPop %',
       'WorldShare'],
      dtype='str')

In [140]:
data.columns = previousNames  # Vorherige Namen wiederherstellen

In [141]:
data

,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

### Daten speichern

Mit den to_... Funktionen können Daten gespeichert werden

Können auch verwendet werden, um Daten in andere Formate zu konvertieren (read -> to ohne/wenige Zwischenschritte)

In [147]:
data.to_csv("Data/PopulationDataFastFertig.csv")

### Daten analysieren

Daten filtern/sortieren/summieren/gruppieren/durchschnittieren/...

In [148]:
data.head(3)

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %

In [149]:
data.tail(3)

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [150]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [155]:
data.head(50)  # Großen Überblick verschaffen

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
Nigeria,206139589,2.58 %,5175990,226,910770,-60000.0,5.4,18,52 %,2.64 %
Bangladesh,164689383,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %
Russia,145934462,0.04 %,62206,9,16376870,182456.0,1.8,40,74 %,1.87 %
Mexico,128932753,1.06 %,1357224,66,1943950,-60000.0,2.1,29,84 %,1.65 %
Japan,126476461,-0.30 %,-383840,347,364555,71560.0,1.4,48,92 %,1.62 %
Ethiopia,114963588,2.57 %,2884858,115,1000000,30000.0,4.3,19,21 %,1.47 %
Philippines,109581078,1.35 %,1464463,368,298170,-67152.0,2.6,26,47 %,1.41 %
Egypt,102334404,1.94 %,1946331,103,995450,-38033.0,3.3,25,43 %,1.31 %
Vietnam,97338579,0.91 %,876473,314,310070,-80000.0,2.1,32,38 %,1.25 %
DR Congo,89561403,3.19 %,2770836,40,2267050,23861.0,6.0,17,46 %,1.15 %
Turkey,84339067,1.09 %,909452,110,769630,283922.0,2.1,32,76 %,1.08 %
Iran,83992949,1.30 %,1079043,52,1628550,-55000.0,2.2,32,76 %,1.08 %
Germany,83783942,0.32 %,266897,240,348560,543822.0,1.6,46,76 %,1.07 %
Thailand,69799978,0.25 %,174396,137,510890,19444.0,1.5,40,51 %,0.90 %
United Kingdom,67886011,0.53 %,355839,281,241930,260650.0,1.8,40,83 %,0.87 %
France,65273511,0.22 %,143783,119,547557,36527.0,1.9,42,82 %,0.84 %
Italy,60461826,-0.15 %,-88249,206,294140,148943.0,1.3,47,69 %,0.78 %
Tanzania,59734218,2.98 %,1728755,67,885800,-40076.0,4.9,18,37 %,0.77 %
South Africa,59308690,1.28 %,750420,49,1213090,145405.0,2.4,28,67 %,0.76 %
Myanmar,54409800,0.67 %,364380,83,653290,-163313.0,2.2,29,31 %,0.70 %
Kenya,53771296,2.28 %,1197323,94,569140,-10000.0,3.5,20,28 %,0.69 %
South Korea,51269185,0.09 %,43877,527,97230,11731.0,1.1,44,82 %,0.66 %
Colombia,50882891,1.08 %,543448,46,1109500,204796.0,1.8,31,80 %,0.65 %
Spain,46754778,0.04 %,18002,94,498800,40000.0,1.3,45,80 %,0.60 %
Uganda,45741007,3.32 %,1471413,229,199810,168694.0,5.0,17,26 %,0.59 %
Argentina,45195774,0.93 %,415097,17,2736690,4800.0,2.3,32,93 %,0.58 %
Algeria,43851044,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
Sudan,43849260,2.42 %,1036022,25,1765048,-50000.0,4.4,20,35 %,0.56 %
Ukraine,43733762,-0.59 %,-259876,75,579320,10000.0,1.4,41,69 %,0.56 %
Iraq,40222493,2.32 %,912710,93,434320,7834.0,3.7,21,73 %,0.52 %
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %
Poland,37846611,-0.11 %,-41157,124,306230,-29395.0,1.4,42,60 %,0.49 %
Canada,37742154,0.89 %,331107,4,9093510,242032.0,1.5,41,81 %,0.48 %
Morocco,36910560,1.20 %,438791,83,446300,-51419.0,2.4,30,64 %,0.47 %
Saudi Arabia,34813871,1.59 %,545343,16,2149690,134979.0,2.3,32,84 %,0.45 %
Uzbekistan,33469203,1.48 %,487487,79,425400,-8863.0,2.4,28,50 %,0.43 %
Peru,32971854,1.42 %,461401,26,1280000,99069.0,2.3,31,79 %,0.42 %
Angola,32866272,3.27 %,1040977,26,1246700,6413.0,5.6,17,67 %,0.42 %
Malaysia,32365999,1.30 %,416222,99,328550,50000.0,2.0,30,78 %,0.42 %
Mozambique,31255435,2.93 %,889399,40,786380,-5000.0,4.9,18,38 %,0.40 %
Ghana,31072940,2.15 %,655084,137,227540,-10000.0,3.9,22,57 %,0.40 %
Yemen,29825964,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Nepal,29136808,1.85 %,528098,203,143350,41710.0,1.9,25,21 %,0.37 %
Venezuela,28435940,-0.28 %,-79889,32,882050,-653249.0,2.3,30,N.A.,0.36 %

#### Sortieren
- sort_index
- sort_values(Spaltenname(n))

In [162]:
data.sort_index()
data.sort_index(ascending=False)  # Reihenfolge ändern

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
Zimbabwe,14862924,1.48 %,217456,38,386850,-116858.0,3.6,19,38 %,0.19 %
Zambia,18383955,2.93 %,522925,25,743390,-8000.0,4.7,18,45 %,0.24 %
Yemen,29825964,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Western Sahara,597339,2.55 %,14876,2,266000,5582.0,2.4,28,87 %,0.01 %
Wallis & Futuna,11239,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
...,...,...,...,...,...,...,...,...,...,...
Andorra,77265,0.16 %,123,164,470,NaN,N.A.,N.A.,88 %,0.00 %
American Samoa,55191,-0.22 %,-121,276,200,NaN,N.A.,N.A.,88 %,0.00 %
Algeria,43851044,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
Albania,2877797,-0.11 %,-3120,105,27400,-14000.0,1.6,36,63 %,0.04 %
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %

In [165]:
data.sort_values("Pop", ascending=False)  # Nach Spaltennamen sortieren

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [167]:
data.sort_values(["MedAge", "Pop"]).head(20)  # Subsequente Sortierungen

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
Niger,24206644,3.84 %,895929,19,1266700,4000.0,7.0,15,17 %,0.31 %
Mali,20250833,3.02 %,592802,17,1220190,-40000.0,5.9,16,44 %,0.26 %
Burundi,11890784,3.12 %,360204,463,25680,2001.0,5.5,17,14 %,0.15 %
Somalia,15893222,2.92 %,450317,25,627340,-40000.0,6.1,17,47 %,0.20 %
Chad,16425864,3.00 %,478988,13,1259200,2000.0,5.8,17,23 %,0.21 %
Angola,32866272,3.27 %,1040977,26,1246700,6413.0,5.6,17,67 %,0.42 %
Uganda,45741007,3.32 %,1471413,229,199810,168694.0,5.0,17,26 %,0.59 %
DR Congo,89561403,3.19 %,2770836,40,2267050,23861.0,6.0,17,46 %,1.15 %
Gambia,2416668,2.94 %,68962,239,10120,-3087.0,5.3,18,59 %,0.03 %
Central African Republic,4829767,1.78 %,84582,8,622980,-40000.0,4.8,18,43 %,0.06 %
Guinea,13132795,2.83 %,361549,53,245720,-4000.0,4.7,18,39 %,0.17 %
Zambia,18383955,2.93 %,522925,25,743390,-8000.0,4.7,18,45 %,0.24 %
Malawi,19129952,2.69 %,501205,203,94280,-16053.0,4.3,18,18 %,0.25 %
Burkina Faso,20903273,2.86 %,581895,76,273600,-25000.0,5.2,18,31 %,0.27 %
Mozambique,31255435,2.93 %,889399,40,786380,-5000.0,4.9,18,38 %,0.40 %
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %
Tanzania,59734218,2.98 %,1728755,67,885800,-40076.0,4.9,18,37 %,0.77 %
Nigeria,206139589,2.58 %,5175990,226,910770,-60000.0,5.4,18,52 %,2.64 %
Sao Tome & Principe,219159,1.91 %,4103,228,960,-1680.0,4.4,19,74 %,0.00 %
Guinea-Bissau,1968001,2.45 %,47079,70,28120,-1399.0,4.5,19,45 %,0.03 %

#### Daten filtern
- Normaler Index (data[...]): Spaltenfilterung
- loc: Zeilenfilterung
- iloc: Indexloc, Zeilenfilterung nach Zahlen

In [168]:
data["Pop"]

Country
China               1439323776
India               1380004385
United States        331002651
Indonesia            273523615
Pakistan             220892340
                       ...
Montserrat                4992
Falkland Islands          3480
Niue                      1626
Tokelau                   1357
Vatican State              801
Name: Pop, Length: 235, dtype: int64

In [171]:
data["Pop"] > 10_000_000

Country
China                True
India                True
United States        True
Indonesia            True
Pakistan             True
                    ...
Montserrat          False
Falkland Islands    False
Niue                False
Tokelau             False
Vatican State       False
Name: Pop, Length: 235, dtype: bool

In [172]:
data[data["Pop"] > 10_000_000]

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Greece,10423054,-0.48 %,-50401,81,128900,-16000.0,1.3,46,85 %,0.13 %
Jordan,10203134,1.00 %,101440,115,88780,10220.0,2.8,24,91 %,0.13 %
Portugal,10196709,-0.29 %,-29478,111,91590,-6000.0,1.3,46,66 %,0.13 %
Azerbaijan,10139177,0.91 %,91459,123,82658,1200.0,2.1,32,56 %,0.13 %
Sweden,10099265,0.63 %,62886,25,410340,40000.0,1.9,41,88 %,0.13 %

In [176]:
data[(data["Pop"] > 10_000_000) & (data["Density"] > 1000)]  # Bei mehreren Filterkriterien muss & und | verwenden (nicht and und or), alle Terme müssen eingeklammert sein

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
Bangladesh,164689383,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %

In [179]:
data.loc["China":"Pakistan"]

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %

In [182]:
data.loc["China"]

Pop             1439323776
YearlyChange        0.39 %
NetChange          5540090
Density                153
LandArea           9388211
MigrantsNet      -348399.0
FertRate               1.7
MedAge                  38
UrbanPop              61 %
WorldShare         18.47 %
Name: China, dtype: object

In [181]:
data.loc["China":"Pakistan"]["Pop"]  # Einzelne Spalte aus einer Zeilenmenge

Country
China            1439323776
India            1380004385
United States     331002651
Indonesia         273523615
Pakistan          220892340
Name: Pop, dtype: int64

In [190]:
data.loc["China":"Pakistan", "Pop":"NetChange"]  # Nur bestimmte Spalten auswählen

                      Pop YearlyChange  NetChange
Country
China          1439323776       0.39 %    5540090
India          1380004385       0.99 %   13586631
United States   331002651       0.59 %    1937734
Indonesia       273523615       1.07 %    2898047
Pakistan        220892340       2.00 %    4327022

In [193]:
data.loc[:, "Pop": "NetChange"]  # Alle Zeilen mit bestimmten Spalten

                         Pop YearlyChange  NetChange
Country
China             1439323776       0.39 %    5540090
India             1380004385       0.99 %   13586631
United States      331002651       0.59 %    1937734
Indonesia          273523615       1.07 %    2898047
Pakistan           220892340       2.00 %    4327022
...                      ...          ...        ...
Montserrat              4992       0.06 %          3
Falkland Islands        3480       3.05 %        103
Niue                    1626       0.68 %         11
Tokelau                 1357       1.27 %         17
Vatican State            801       0.25 %          2

[235 rows x 3 columns]

In [207]:
data.loc[:, ("Pop", "WorldShare")]  # Bestimmte Spalten entnehmen mit ( ) -> Liste

                         Pop WorldShare
Country
China             1439323776    18.47 %
India             1380004385    17.70 %
United States      331002651     4.25 %
Indonesia          273523615     3.51 %
Pakistan           220892340     2.83 %
...                      ...        ...
Montserrat              4992     0.00 %
Falkland Islands        3480     0.00 %
Niue                    1626     0.00 %
Tokelau                 1357     0.00 %
Vatican State            801     0.00 %

[235 rows x 2 columns]

In [202]:
data.index[data.index.str.contains("A") | data.index.str.contains("B")]  # Spalte nach allen Texten suchen die ein A oder B enthalten

Index(['Brazil', 'Bangladesh', 'South Africa', 'Argentina', 'Algeria',
       'Afghanistan', 'Saudi Arabia', 'Angola', 'Australia', 'Burkina Faso',
       'Benin', 'Burundi', 'Bolivia', 'Belgium', 'Azerbaijan',
       'United Arab Emirates', 'Belarus', 'Austria', 'Bulgaria',
       'Central African Republic', 'Bosnia and Herzegovina', 'Armenia',
       'Albania', 'Botswana', 'Guinea-Bissau', 'Bahrain', 'Bhutan', 'Brunei',
       'Belize', 'Bahamas', 'Barbados', 'Aruba', 'Antigua and Barbuda',
       'Andorra', 'Bermuda', 'American Samoa', 'British Virgin Islands',
       'Anguilla', 'Saint Barthelemy'],
      dtype='str', name='Country')

In [205]:
data.loc[data.index[data.index.str.contains("A") | data.index.str.contains("B")]]  # Finde alle Datensätze die A oder B enthalten (beim Country)

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
Brazil,212559417,0.72 %,1509890,25,8358140,21200.0,1.7,33,88 %,2.73 %
Bangladesh,164689383,1.01 %,1643222,1265,130170,-369501.0,2.1,28,39 %,2.11 %
South Africa,59308690,1.28 %,750420,49,1213090,145405.0,2.4,28,67 %,0.76 %
Argentina,45195774,0.93 %,415097,17,2736690,4800.0,2.3,32,93 %,0.58 %
Algeria,43851044,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %
Saudi Arabia,34813871,1.59 %,545343,16,2149690,134979.0,2.3,32,84 %,0.45 %
Angola,32866272,3.27 %,1040977,26,1246700,6413.0,5.6,17,67 %,0.42 %
Australia,25499884,1.18 %,296686,3,7682300,158246.0,1.8,38,86 %,0.33 %
Burkina Faso,20903273,2.86 %,581895,76,273600,-25000.0,5.2,18,31 %,0.27 %
Benin,12123200,2.73 %,322049,108,112760,-2000.0,4.9,19,48 %,0.16 %
Burundi,11890784,3.12 %,360204,463,25680,2001.0,5.5,17,14 %,0.15 %
Bolivia,11673021,1.39 %,159921,11,1083300,-9504.0,2.8,26,69 %,0.15 %
Belgium,11589623,0.44 %,50295,383,30280,48000.0,1.7,42,98 %,0.15 %
Azerbaijan,10139177,0.91 %,91459,123,82658,1200.0,2.1,32,56 %,0.13 %
United Arab Emirates,9890402,1.23 %,119873,118,83600,40000.0,1.4,33,86 %,0.13 %
Belarus,9449323,-0.03 %,-3088,47,202910,8730.0,1.7,40,79 %,0.12 %
Austria,9006398,0.57 %,51296,109,82409,65000.0,1.5,43,57 %,0.12 %
Bulgaria,6948445,-0.74 %,-51674,64,108560,-4800.0,1.6,45,76 %,0.09 %
Central African Republic,4829767,1.78 %,84582,8,622980,-40000.0,4.8,18,43 %,0.06 %
Bosnia and Herzegovina,3280819,-0.61 %,-20181,64,51000,-21585.0,1.3,43,52 %,0.04 %
Armenia,2963243,0.19 %,5512,104,28470,-4998.0,1.8,35,63 %,0.04 %
Albania,2877797,-0.11 %,-3120,105,27400,-14000.0,1.6,36,63 %,0.04 %
Botswana,2351627,2.08 %,47930,4,566730,3000.0,2.9,24,73 %,0.03 %
Guinea-Bissau,1968001,2.45 %,47079,70,28120,-1399.0,4.5,19,45 %,0.03 %
Bahrain,1701575,3.68 %,60403,2239,760,47800.0,2.0,32,89 %,0.02 %
Bhutan,771608,1.12 %,8516,20,38117,320.0,2.0,28,46 %,0.01 %
Brunei,437479,0.97 %,4194,83,5270,0.0,1.8,32,80 %,0.01 %
Belize,397628,1.86 %,7275,17,22810,1200.0,2.3,25,46 %,0.01 %
Bahamas,393244,0.97 %,3762,39,10010,1000.0,1.8,32,86 %,0.01 %
Barbados,287375,0.12 %,350,668,430,-79.0,1.6,40,31 %,0.00 %
Aruba,106766,0.43 %,452,593,180,201.0,1.9,41,44 %,0.00 %
Antigua and Barbuda,97929,0.84 %,811,223,440,0.0,2.0,34,26 %,0.00 %
Andorra,77265,0.16 %,123,164,470,NaN,N.A.,N.A.,88 %,0.00 %
Bermuda,62278,-0.36 %,-228,1246,50,NaN,N.A.,N.A.,97 %,0.00 %
American Samoa,55191,-0.22 %,-121,276,200,NaN,N.A.,N.A.,88 %,0.00 %
British Virgin Islands,30231,0.67 %,201,202,150,NaN,N.A.,N.A.,52 %,0.00 %
Anguilla,15003,0.90 %,134,167,90,NaN,N.A.,N.A.,N.A.,0.00 %
Saint Barthelemy,9877,0.30 %,30,470,21,NaN,N.A.,N.A.,0 %,0.00 %

In [216]:
data["MedAge"].value_counts()  # Anzahlen von identischen Werten pro Spalte suchen

MedAge
N.A.    34
19      14
28      12
32      11
43      11
18      10
42      10
20       9
30       8
38       7
40       7
26       7
22       7
17       6
31       6
34       6
24       6
33       5
29       5
44       5
45       5
41       5
21       5
23       4
25       4
27       4
37       4
36       4
46       3
35       3
39       3
47       2
48       1
15       1
16       1
Name: count, dtype: int64

In [222]:
data.value_counts()  # Alle Zeilen auf Eindeutigkeit prüfen

Pop         YearlyChange  NetChange  Density  LandArea  MigrantsNet  FertRate  MedAge  UrbanPop  WorldShare
1439323776  0.39 %         5540090   153      9388211   -348399.0    1.7       38      61 %      18.47 %       1
1380004385  0.99 %         13586631  464      2973190   -532687.0    2.2       28      35 %      17.70 %       1
331002651   0.59 %         1937734   36       9147420    954806.0    1.8       38      83 %      4.25 %        1
273523615   1.07 %         2898047   151      1811570   -98955.0     2.3       30      56 %      3.51 %        1
220892340   2.00 %         4327022   287      770880    -233379.0    3.6       23      35 %      2.83 %        1
                                                                                                              ..
106766      0.43 %         452       593      180        201.0       1.9       41      44 %      0.00 %        1
105695      1.15 %         1201      147      720       -800.0       3.6       22      24 %      0.00 %        1
104425      -0.15 %       -153       298      350       -451.0       2.0       43      96 %      0.00 %        1
98347       0.62 %         608       214      460       -200.0       2.5       34      56 %      0.00 %        1
97929       0.84 %         811       223      440        0.0         2.0       34      26 %      0.00 %        1
Name: count, Length: 201, dtype: int64

#### Gruppierung

Datensätze anhand eines Kriteriums in Gruppen aufteilen

Danach können diese Gruppen separat analysiert werden, oder auf jede Gruppe eine Auswertung ausführen

In [231]:
data.groupby("MedAge")

In [232]:
data.groupby("MedAge").get_group("19")["Pop"].mean()  # Einzelne Gruppe auswerten

np.float64(18241182.64285714)

In [233]:
data.groupby("MedAge")["Pop"].mean()  # Alle Gruppen auswerten

MedAge
15      2.420664e+07
16      2.025083e+07
17      3.539643e+07
18      4.148540e+07
19      1.824118e+07
20      1.939652e+07
21      9.621932e+06
22      7.686515e+06
23      6.028827e+07
24      7.213284e+06
25      3.304188e+07
26      2.510786e+07
27      2.088666e+06
28      1.398790e+08
29      4.693030e+07
30      4.894655e+07
31      1.847800e+07
32      3.284957e+07
33      4.789470e+07
34      3.726593e+06
35      1.595275e+07
36      2.161582e+06
37      1.772735e+06
38      2.590871e+08
39      1.120258e+06
40      4.277205e+07
41      1.942832e+07
42      1.717237e+07
43      7.631299e+06
44      1.210433e+07
45      1.320029e+07
46      3.480124e+07
47      3.041855e+07
48      1.264765e+08
N.A.    3.333179e+04
Name: Pop, dtype: float64

In [234]:
for x in data.groupby("MedAge")["Pop"].mean():  # Absolute Werte ausgeben
    print(int(x))

24206644
20250833
35396425
41485399
18241182
19396523
9621932
7686515
60288272
7213284
33041880
25107858
2088666
139879041
46930304
48946550
18478003
32849571
47894699
3726593
15952753
2161581
1772735
259087065
1120258
42772052
19428317
17172367
7631298
12104325
13200286
34801235
30418545
126476461
33331

#### Datensets verbinden

In [210]:
x = pd.DataFrame(np.vstack([data, data]))

In [213]:
x.columns = data.columns  # Spaltennamen übernehmen

In [214]:
x

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
0,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
465,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
466,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
467,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
468,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
469,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %