# Fehlerbehandlung mit Pandas

Fehler in den Daten selbst beheben

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("Data/PopulationDataFastFertig.csv", decimal=".", thousands=",", delimiter=",", index_col="Country")

In [3]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

## Probleme mit den Daten
- Prozentzeichen
- NaN
- N.A. (String)
- Datentypen

### NaN
- isnull(), isna()
- notnull(), notna()

In [4]:
data.isnull()  # Alle Datensätze finden, mit leeren Werten

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,False,False,False,False,False,False,False,False,False,False
India,False,False,False,False,False,False,False,False,False,False
United States,False,False,False,False,False,False,False,False,False,False
Indonesia,False,False,False,False,False,False,False,False,False,False
Pakistan,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
Montserrat,False,False,False,False,False,True,False,False,False,False
Falkland Islands,False,False,False,False,False,True,False,False,False,False
Niue,False,False,False,False,False,True,False,False,False,False
Tokelau,False,False,False,False,False,True,False,False,False,False
Vatican State,False,False,False,False,False,True,False,False,False,False

In [5]:
data.isnull().value_counts()  # Überblick über alle Null-Werte in der Tabelle

Pop    YearlyChange  NetChange  Density  LandArea  MigrantsNet  FertRate  MedAge  UrbanPop  WorldShare
False  False         False      False    False     False        False     False   False     False         201
                                                   True         False     False   False     False          34
Name: count, dtype: int64

### NaN befüllen
- manuell
- ffill(), bfill()

In [6]:
data.ffill()  # Forwardfill, nimmt den letzten Wert (von oben) und kopiert diesen hinunter; bfill nimmt den letzten Wert von unten

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,0.0,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,0.0,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,0.0,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,0.0,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,0.0,N.A.,N.A.,N.A.,0.00 %

In [7]:
data.bfill(inplace=True)  # Änderungen übernehmen

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

#### Manuelles befüllen

Spalte auswählen, Null-Werte innerhalb dieser Spalte finden, Null-Werte mit = befüllen, Spalten zurückschreiben ins Datenset

In [8]:
b = data["MigrantsNet"]

In [9]:
b.isna()  # Filterung der alleinigen Spalte nach Null-Werten

Country
China               False
India               False
United States       False
Indonesia           False
Pakistan            False
                    ...
Montserrat           True
Falkland Islands     True
Niue                 True
Tokelau              True
Vatican State        True
Name: MigrantsNet, Length: 235, dtype: bool

In [10]:
b[b.isna()]  # Filterung auf die Spalte selbst anwenden

Country
Isle of Man                NaN
Andorra                    NaN
Dominica                   NaN
Cayman Islands             NaN
Bermuda                    NaN
Marshall Islands           NaN
Northern Mariana Islands   NaN
Greenland                  NaN
American Samoa             NaN
Saint Kitts & Nevis        NaN
Faeroe Islands             NaN
Sint Maarten               NaN
Monaco                     NaN
Turks and Caicos           NaN
Saint Martin               NaN
Liechtenstein              NaN
San Marino                 NaN
Gibraltar                  NaN
British Virgin Islands     NaN
Caribbean Netherlands      NaN
Palau                      NaN
Cook Islands               NaN
Anguilla                   NaN
Tuvalu                     NaN
Wallis & Futuna            NaN
Nauru                      NaN
Saint Barthelemy           NaN
Saint Helena               NaN
Saint Pierre & Miquelon    NaN
Montserrat                 NaN
Falkland Islands           NaN
Niue                       NaN
Tokelau                    NaN
Vatican State              NaN
Name: MigrantsNet, dtype: float64

In [11]:
b[b.isna()] = 0  # Neuen Wert hineinschreiben

In [12]:
b

Country
China              -348399.0
India              -532687.0
United States       954806.0
Indonesia           -98955.0
Pakistan           -233379.0
                      ...
Montserrat               0.0
Falkland Islands         0.0
Niue                     0.0
Tokelau                  0.0
Vatican State            0.0
Name: MigrantsNet, Length: 235, dtype: float64

In [13]:
data["MigrantsNet"] = b

In [14]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,0.0,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,0.0,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,0.0,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,0.0,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,0.0,N.A.,N.A.,N.A.,0.00 %

In [15]:
# Eigene Funktion schreiben
def fixNaN(columnName: str):
    col = data[columnName]
    b = col[col.isnull()]
    col[b] = 0
    data[columnName] = col

In [16]:
fixNaN("LandArea")  # Funktion kann jetzt mit Spaltenname einfach verwendet werden

### Prozentzeichen

Hier wird die string-Replace Funktion verwendet

In [17]:
data["YearlyChange"].replace(" %", "", regex=True)  # Hier muss regex=True verwendet werden (weil keine Ahnung)

Country
China               0.39
India               0.99
United States       0.59
Indonesia           1.07
Pakistan            2.00
                    ...
Montserrat          0.06
Falkland Islands    3.05
Niue                0.68
Tokelau             1.27
Vatican State       0.25
Name: YearlyChange, Length: 235, dtype: str

In [18]:
data["YearlyChange"] = data["YearlyChange"].replace(" %", "", regex=True)

In [19]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05,103,0,12170,0.0,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68,11,6,260,0.0,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27,17,136,10,0.0,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25,2,2003,0,0.0,N.A.,N.A.,N.A.,0.00 %

In [20]:
def fixPct(columnName: str):
    data[columnName] = data[columnName].replace(" %", "", regex=True)

In [21]:
data.columns

Index(['Pop', 'YearlyChange', 'NetChange', 'Density', 'LandArea',
       'MigrantsNet', 'FertRate', 'MedAge', 'UrbanPop', 'WorldShare'],
      dtype='str')

In [22]:
for col in data.columns:  # Aus jeder Spalte % entfernen
    fixPct(col)

In [23]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,N.A.,N.A.,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,N.A.,N.A.,66,0.00
Niue,1626,0.68,11,6,260,0.0,N.A.,N.A.,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,N.A.,N.A.,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,N.A.,N.A.,N.A.,0.00

### N.A.
Selbes Schema wie Prozentzeichen

In [24]:
def fixNA(columnName: str, newValue):
    data[columnName] = data[columnName].replace("N.A.", newValue)

In [25]:
for col in data.columns:  # Aus jeder Spalte N.A. entfernen
    fixNA(col, "0")

In [26]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,0,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,0,0,66,0.00
Niue,1626,0.68,11,6,260,0.0,0,0,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,0,0,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,0,0,0,0.00

### Datentypen

Bei der Behebung von Fehlern werden die Typen nicht automatisch angepasst

Gute Typen verkleinern das Datenset und erhöhen die Performance

In [27]:
data.info()

<class 'pandas.DataFrame'>
Index: 235 entries, China to Vatican State
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Pop           235 non-null    int64
 1   YearlyChange  235 non-null    str
 2   NetChange     235 non-null    int64
 3   Density       235 non-null    int64
 4   LandArea      235 non-null    int64
 5   MigrantsNet   235 non-null    float64
 6   FertRate      235 non-null    str
 7   MedAge        235 non-null    str
 8   UrbanPop      235 non-null    str
 9   WorldShare    235 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 28.3+ KB

In [28]:
data.convert_dtypes().info()  # MigrantsNet float -> Int64

<class 'pandas.DataFrame'>
Index: 235 entries, China to Vatican State
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Pop           235 non-null    Int64
 1   YearlyChange  235 non-null    string
 2   NetChange     235 non-null    Int64
 3   Density       235 non-null    Int64
 4   LandArea      235 non-null    Int64
 5   MigrantsNet   235 non-null    Int64
 6   FertRate      235 non-null    string
 7   MedAge        235 non-null    string
 8   UrbanPop      235 non-null    string
 9   WorldShare    235 non-null    string
dtypes: Int64(5), string(5)
memory usage: 29.4+ KB

convert_dtypes ist nicht sonderlich akkurat -> manuell

astype(Typ): Forciert eine Konvertierung; im Vorhinein muss klar sein, welcher Typ optimal ist

In [29]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,0,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,0,0,66,0.00
Niue,1626,0.68,11,6,260,0.0,0,0,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,0,0,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,0,0,0,0.00

In [30]:
data["Pop"] = data["Pop"].astype(np.int32)

In [31]:
def fixType(columnName: str, newType):
    data[columnName] = data[columnName].astype(newType)

In [32]:
fixType("YearlyChange", np.float32)

In [37]:
fixType("NetChange", np.int32)

In [38]:
fixType("Density", np.int16)

In [39]:
data

,Pop,YearlyChange,NetChange,Density,LandArea,MigrantsNet,FertRate,MedAge,UrbanPop,WorldShare
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,0,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,0,0,66,0.00
Niue,1626,0.68,11,6,260,0.0,0,0,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,0,0,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,0,0,0,0.00

In [40]:
fixType("LandArea", np.int32)

In [41]:
fixType("MigrantsNet", np.int32)

In [42]:
fixType("FertRate", np.float32)

In [43]:
fixType("MedAge", np.int8)

In [44]:
fixType("UrbanPop", np.int8)

In [45]:
fixType("WorldShare", np.float32)

In [46]:
data.info()

<class 'pandas.DataFrame'>
Index: 235 entries, China to Vatican State
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Pop           235 non-null    int32
 1   YearlyChange  235 non-null    float32
 2   NetChange     235 non-null    int32
 3   Density       235 non-null    int16
 4   LandArea      235 non-null    int32
 5   MigrantsNet   235 non-null    int32
 6   FertRate      235 non-null    float32
 7   MedAge        235 non-null    int8
 8   UrbanPop      235 non-null    int8
 9   WorldShare    235 non-null    float32
dtypes: float32(3), int16(1), int32(4), int8(2)
memory usage: 17.3+ KB

In [48]:
17.3 / 29.4  #~41% Ersparnis

0.58843537414966

In [55]:
data.to_csv("Data/PopulationDataFertig.csv")

Weitere Dinge die dem Björn eingefallen sind

In [49]:
data["ABC"] = np.arange(len(data))  # Neue Spalte hinzufügen

In [50]:
data["FertRate"].str.index(".")

AttributeError: Can only use .str accessor with string values, not floating

In [51]:
data["FertRate"].str[2:]  # Alle Zeichen nach dem ersten Punkt

AttributeError: Can only use .str accessor with string values, not floating